### ISSUE TITLE
Deal with metadata errors

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq-webview#144] opened 2022-03-24 13:59 UTC
It seems the UI gets stuck when invalid metrics are included, e.g. bogus URL.

**Comment by tilsche** [comment] 2022-05-05 08:59
If a metadata request returns 404, do not add the metric to the legend and do not process it further, just make an error popup "metadata for XX could not be found".

**Comment by bmario** [comment] 2022-05-23 06:39
duplicate of #130

**Closed** 2022-05-25 15:06 UTC
Labels: bug
